declare const _default: (() => {
    env: string;
    name: string;
    port: string;
    serviceMailer: string;
    ocr: string;
    preValidatorEmail: string;
    allowedOrigins: string;
    smsKey: string;
    linkShortener: string;
    validationFront: string;
    broker: string;
    clientSaintGobain: string;
    storageBucket: string;
    departmentAddress: string;
    maintenanceAddress: string;
    RTEEmailInvoices: string;
    RTEEmail: string;
    FATECEmailInvoices: string;
}) & import("@nestjs/config").ConfigFactoryKeyHost<{
    env: string;
    name: string;
    port: string;
    serviceMailer: string;
    ocr: string;
    preValidatorEmail: string;
    allowedOrigins: string;
    smsKey: string;
    linkShortener: string;
    validationFront: string;
    broker: string;
    clientSaintGobain: string;
    storageBucket: string;
    departmentAddress: string;
    maintenanceAddress: string;
    RTEEmailInvoices: string;
    RTEEmail: string;
    FATECEmailInvoices: string;
}>;
export default _default;
